### PR TITLE
Correct evoked field calculation

### PR DESCRIPTION
**Pull request by hoechenberger**
Figured out the issues with the coordinate transforms.

- evoked fields are now appearing in the correct orientation
- dipoles placed outside the brain will emit an error message while "exact solution" checkbox is unticket (case where the checkbox is ticked still needs handling)
- code is really "rapidly developed" (although it took me so long, haha), so _definitely_ will need some refactoring later
- Small graphical glitches, MR slices should be larger (and currently sometimes change their size), <strike>and I believe I broke the color bar labels</strike> But that all should be easy to fix.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@agramfort You can try this at
https://mybinder.org/v2/gh/hoechenberger/dipoles_demo/coord-frame?urlpath=voila%2Frender%2Findex.ipynb

**Comment by agramfort** [comment]
slice selector works for you?

**Comment by hoechenberger** [comment]
> slice selector works for you?

Now it does :D
The amplitude slider does sth strange though, will have to check.

**Comment by hoechenberger** [comment]
@agramfort OK from here on it's only cosmetics, speed, and potentially some bugs in edge cases. Otherwise should be good. Let me know how it works for you!

https://mybinder.org/v2/gh/hoechenberger/dipoles_demo/coord-frame?urlpath=voila%2Frender%2Findex.ipynb

Will merge if you're happy.

**Comment by agramfort** [comment]
ok to merge?

**Comment by hoechenberger** [comment]
@agramfort I'm sometimes getting a weird redraw error on Binder, when I browse slices, sometimes one slice doesn't get redrawn and remains white. I cannot reproduce this locally so I'm a bit clueless… aside from that, it's good to merge…

**Comment by hoechenberger** [comment]
@agramfort Ok I think disabling the crosshair has solved the redrawing issue for me. I'll just leave it off for now, and go ahead and merge.

**Comment by agramfort** [comment]
let's merge then and iterate later

>

**Comment by hoechenberger** [comment]
@agramfort Ok I think disabling the crosshair has solved the redrawing issue for me. I'll just leave it off for now, and go ahead and merge.

**Comment by hoechenberger** [comment]
@agramfort Ok I think disabling the crosshair has solved the redrawing issue for me. I'll just leave it off for now, and go ahead and merge.

**Comment by hoechenberger** [comment]
@agramfort Ok I think disabling the crosshair has solved the redrawing issue for me. I'll just leave it off for now, and go ahead and merge.

**Comment by hoechenberger** [comment]
Apparently this got merged, but Github hiccuped, so the PR wasn't auto-closed. Closing!

**Pull request closed without merging**
